application: sgxmarkets
version: 1
runtime: python
api_version: 1

handlers:
- url: /google198f15972d7d87d0.html
  static_files: templates/googleVerification/google198f15972d7d87d0.html
  upload: templates/googleVerification/google198f15972d7d87d0.html
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /overlay
  static_dir: overlay
- url: /.*
  script: devchat.py
