application: sgxmarkets
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /overlay
  static_dir: overlay
- url: /.*
  script: devchat.py